{% set name = "python-hcl2" %}
{% set version = "3.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-hcl2-{{ version }}.tar.gz
  sha256: 21c76d0b0238f6bd1affa5e990e87676abd3511cd6384e96fba1212fcb71de6a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark-parser >=0.10.0,<0.11.0
    - python >=3.6

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amplify-education/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
