{% set name = "python-hcl2" %}
{% set version = "3.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-hcl2-{{ version }}.tar.gz
  sha256: f6c178d216e9d8ef1ef9fceeb16792cbabfb69d2ae1a73e263974ab6f74489ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - lark-parser >=0.10.0,<0.11.0
    - python >=3.6

test:
  imports:
    - hcl2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/amplify-education/python-hcl2
  summary: A parser for HCL2
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - RohitK89
    - mariusvniekerk
